@extends('layouts.app')
@section('title', 'Clinical Encounter · CityCare Medical Center')
@section('content')
<div style="padding:34px 24px;max-width:1100px">
    @if(session('status'))<div class="status" style="margin-bottom:18px">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="status" style="margin-bottom:18px;background:#fef2f2;color:#991b1b">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
    <div style="display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:24px">
        <div><div style="color:#2563eb;font-size:.74rem;font-weight:900;letter-spacing:.14em">CLINICAL ENCOUNTER</div><h1 style="margin:6px 0">{{ $encounter->encounter_number }}</h1><p style="color:#627d98">{{ $encounter->patient->full_name }} · {{ $encounter->patient->medical_record_number }}</p></div>
        <div style="padding:8px 12px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-weight:800">{{ ucfirst($encounter->status) }}</div>
    </div>
    <div class="card" style="padding:24px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px">
        <div><strong>Clinician</strong><div style="color:#627d98;margin-top:5px">{{ $encounter->clinician->name }}</div></div><div><strong>Department</strong><div style="color:#627d98;margin-top:5px">{{ $encounter->department->name }}</div></div><div><strong>Service point</strong><div style="color:#627d98;margin-top:5px">{{ $encounter->servicePoint->name }}</div></div><div><strong>Started</strong><div style="color:#627d98;margin-top:5px">{{ $encounter->started_at?->format('d M Y H:i') }}</div></div><div style="grid-column:1/-1"><strong>Summary</strong><div style="color:#627d98;margin-top:5px">{{ $encounter->summary ?: 'No summary recorded yet.' }}</div></div>
    </div>

    <div class="card" style="margin-top:18px;padding:24px"><h2 style="margin-top:0">Vitals</h2>@forelse($encounter->vitals as $vital)<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><strong>{{ $vital->recorded_at?->format('d M Y H:i') }}</strong><div style="color:#627d98;margin-top:5px">Temperature: {{ $vital->temperature ?? '—' }} · Pulse: {{ $vital->pulse ?? '—' }} · Respiratory rate: {{ $vital->respiratory_rate ?? '—' }} · Blood pressure: {{ $vital->blood_pressure_systolic ?? '—' }}/{{ $vital->blood_pressure_diastolic ?? '—' }} · SpO₂: {{ $vital->oxygen_saturation ?? '—' }}</div><div style="color:#627d98;margin-top:4px">Recorded by {{ $vital->recorder->name }}</div></div>@empty<p style="color:#627d98">No vitals recorded yet.</p>@endforelse
    @if($encounter->isOpen() && auth()->user()->hasPermissionTo('clinical.vitals.manage'))<form method="POST" action="{{ route('encounters.vitals.store', $encounter) }}" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:20px">@csrf<h3 style="grid-column:1/-1;margin:0">Record vitals</h3><input name="temperature" value="{{ old('temperature') }}" placeholder="Temperature"><input name="pulse" value="{{ old('pulse') }}" placeholder="Pulse"><input name="respiratory_rate" value="{{ old('respiratory_rate') }}" placeholder="Respiratory rate"><input name="blood_pressure_systolic" value="{{ old('blood_pressure_systolic') }}" placeholder="Systolic BP"><input name="blood_pressure_diastolic" value="{{ old('blood_pressure_diastolic') }}" placeholder="Diastolic BP"><input name="oxygen_saturation" value="{{ old('oxygen_saturation') }}" placeholder="Oxygen saturation"><button style="justify-self:start;background:#2563eb;color:#fff;border:0;border-radius:10px;padding:12px 16px;font-weight:800">Save vitals</button></form>@endif</div>

    <div class="card" style="margin-top:18px;padding:24px"><h2 style="margin-top:0">Clinical notes</h2>@forelse($encounter->notes as $note)<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><div style="display:flex;justify-content:space-between"><strong>{{ ucfirst($note->type ?? 'Clinical') }} note</strong><span>{{ ucfirst($note->status) }}</span></div><div style="color:#627d98;margin-top:5px">{{ $note->content }}</div><div style="color:#627d98;margin-top:4px">By {{ $note->author->name }}</div>@if(!$note->isFinalized() && auth()->user()->hasPermissionTo('clinical.notes.manage'))<form method="POST" action="{{ route('encounters.notes.finalize', $note) }}" style="margin-top:8px">@csrf<button style="background:#15803d;color:#fff;border:0;border-radius:8px;padding:8px 12px;font-weight:700">Finalize note</button></form>@endif</div>@empty<p style="color:#627d98">No clinical notes recorded yet.</p>@endforelse
    @if($encounter->isOpen() && auth()->user()->hasPermissionTo('clinical.notes.manage'))<form method="POST" action="{{ route('encounters.notes.store', $encounter) }}" style="display:grid;gap:10px;margin-top:20px">@csrf<h3 style="margin:0">Add clinical note</h3><select name="type"><option value="progress">Progress note</option><option value="consultation">Consultation note</option><option value="other">Other</option></select><textarea name="content" rows="5" placeholder="Clinical note" required>{{ old('content') }}</textarea><label><input type="checkbox" name="finalize" value="1"> Finalize immediately</label><button style="justify-self:start;background:#2563eb;color:#fff;border:0;border-radius:10px;padding:12px 16px;font-weight:800">Save note</button></form>@endif</div>

    <div class="card" style="margin-top:18px;padding:24px"><h2 style="margin-top:0">Diagnoses</h2>@forelse($encounter->diagnoses as $diagnosis)<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><div style="display:flex;justify-content:space-between;gap:12px"><strong>{{ $diagnosis->diagnosis }}</strong><span style="font-weight:800;color:#2563eb">{{ ucfirst($diagnosis->type) }}</span></div><div style="color:#627d98;margin-top:4px">{{ $diagnosis->diagnosis_code ?: 'No diagnosis code' }} · Recorded by {{ $diagnosis->recorder->name }}</div>@if($diagnosis->notes)<div style="color:#627d98;margin-top:6px">{{ $diagnosis->notes }}</div>@endif</div>@empty<p style="color:#627d98">No diagnoses recorded yet.</p>@endforelse
        @if($encounter->isOpen() && auth()->user()->hasPermissionTo('clinical.diagnoses.manage'))<form method="POST" action="{{ route('encounters.diagnoses.store', $encounter) }}" style="display:grid;gap:12px;margin-top:20px">@csrf<h3 style="margin:0">Record diagnosis</h3><input name="diagnosis" value="{{ old('diagnosis') }}" placeholder="Diagnosis" required><input name="diagnosis_code" value="{{ old('diagnosis_code') }}" placeholder="Diagnosis code (optional)"><select name="type"><option value="primary">Primary diagnosis</option><option value="secondary">Secondary diagnosis</option></select><textarea name="notes" rows="4" placeholder="Clinical notes (optional)">{{ old('notes') }}</textarea><button style="justify-self:start;background:#2563eb;color:#fff;border:0;border-radius:10px;padding:12px 16px;font-weight:800">Record diagnosis</button></form>@endif</div>

    @if($encounter->treatmentPlans->isNotEmpty() || ($encounter->isOpen() && auth()->user()->hasPermissionTo('clinical.treatment-plans.manage')))<div class="card" style="margin-top:18px;padding:24px"><h2 style="margin-top:0">Treatment plans</h2>@forelse($encounter->treatmentPlans as $plan)<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><strong>Plan #{{ $plan->id }}</strong><span style="margin-left:8px">{{ ucfirst($plan->status) }}</span><div style="color:#627d98;margin-top:4px">{{ $plan->plan }}</div>@if($plan->isActive() && auth()->user()->hasPermissionTo('clinical.treatment-plans.manage'))<form method="POST" action="{{ route('encounters.treatment-plans.complete', $plan) }}" style="display:inline-block;margin-top:8px">@csrf<button>Complete</button></form><form method="POST" action="{{ route('encounters.treatment-plans.cancel', $plan) }}" style="display:inline-block;margin-top:8px">@csrf<button>Cancel</button></form>@endif</div>@empty<p style="color:#627d98">No treatment plans recorded yet.</p>@endforelse@if($encounter->isOpen() && auth()->user()->hasPermissionTo('clinical.treatment-plans.manage'))<form method="POST" action="{{ route('encounters.treatment-plans.store', $encounter) }}" style="display:grid;gap:10px;margin-top:20px">@csrf<textarea name="plan" required placeholder="Treatment plan">{{ old('plan') }}</textarea><input type="date" name="follow_up_date" value="{{ old('follow_up_date') }}"><button>Create treatment plan</button></form>@endif</div>@endif

    @if($encounter->referrals->isNotEmpty() || ($encounter->isOpen() && auth()->user()->hasPermissionTo('clinical.referrals.manage')))<div class="card" style="margin-top:18px;padding:24px"><h2 style="margin-top:0">Referrals</h2>@forelse($encounter->referrals as $referral)<div style="padding:12px 0;border-bottom:1px solid #e5e7eb"><strong>Referral #{{ $referral->id }} · {{ $referral->referred_to }}</strong><span style="margin-left:8px">{{ ucfirst($referral->status) }}</span><div style="color:#627d98;margin-top:4px">{{ $referral->reason }}</div>@if($referral->attachments->isNotEmpty())<div style="margin-top:8px"><strong>Attachments</strong>@foreach($referral->attachments as $attachment)<div>{{ $attachment->file_name }} @if(auth()->user()->hasPermissionTo('clinical.referrals.manage'))<form method="POST" action="{{ route('encounters.referrals.attachments.destroy', $attachment) }}" style="display:inline">@csrf @method('DELETE')<button>Delete</button></form>@endif</div>@endforeach</div>@endif@if(auth()->user()->hasPermissionTo('clinical.referrals.manage'))<form method="POST" enctype="multipart/form-data" action="{{ route('encounters.referrals.attachments.store', $referral) }}" style="margin-top:8px">@csrf<input type="file" name="file" required><button>Upload</button></form>@endif</div>@empty<p style="color:#627d98">No referrals recorded yet.</p>@endforelse@if($encounter->isOpen() && auth()->user()->hasPermissionTo('clinical.referrals.manage'))<form method="POST" action="{{ route('encounters.referrals.store', $encounter) }}" style="display:grid;gap:10px;margin-top:20px">@csrf<input name="referred_to_department" required placeholder="Referred to department"><textarea name="reason" required placeholder="Reason"></textarea><select name="priority"><option value="routine">Routine</option><option value="urgent">Urgent</option><option value="emergency">Emergency</option></select><textarea name="notes" placeholder="Notes"></textarea><button>Create referral</button></form>@endif</div>@endif

    @if($encounter->isOpen())<div class="card" style="margin-top:18px;padding:24px"><h2 style="margin-top:0">Close encounter</h2><form method="POST" action="{{ route('encounters.close', $encounter) }}" style="display:grid;gap:12px">@csrf<textarea name="summary" rows="5" placeholder="Enter consultation closing summary…">{{ $encounter->summary }}</textarea><div style="display:flex;gap:10px"><button style="background:#15803d;color:#fff;border:0;border-radius:10px;padding:12px 16px;font-weight:800">Close encounter</button><button formmethod="POST" formaction="{{ route('encounters.cancel', $encounter) }}" style="background:#b91c1c;color:#fff;border:0;border-radius:10px;padding:12px 16px;font-weight:800">Cancel encounter</button></div></form></div>@endif
</div>
@endsection
