<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Patients · CityCare Medical Center</title>
<style>
:root{--navy:#082f49;--blue:#2563eb;--sky:#eff6ff;--cream:#f7fafc;--ink:#102a43;--muted:#627d98;--line:#d9e2ec;--yellow:#f4c430;--green:#15803d}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui;color:var(--ink);background:var(--cream)}.shell{min-height:100vh;display:grid;grid-template-columns:240px 1fr}aside{padding:28px 20px;background:linear-gradient(180deg,var(--navy),#0c4a6e);color:#fff}.brand{display:flex;gap:12px;align-items:center;margin-bottom:42px}.mark{width:42px;height:42px;border-radius:12px;background:#fff;color:var(--navy);display:grid;place-items:center;font-weight:900}.brand small{display:block;color:#bae6fd}nav{display:grid;gap:8px}nav a{color:#e0f2fe;text-decoration:none;padding:11px 12px;border-radius:10px}nav a:hover,nav a.active{background:rgba(255,255,255,.1);color:#fff}.logout{margin-top:35px;background:none;border:0;color:#fff;font-weight:800;cursor:pointer}main{padding:34px clamp(22px,4vw,56px);max-width:1450px;width:100%}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:26px}.eyebrow{color:var(--blue);font-size:.74rem;font-weight:900;letter-spacing:.14em}h1{margin:6px 0;font-size:clamp(2rem,4vw,3rem);letter-spacing:-.05em}.muted{color:var(--muted);line-height:1.5}.btn{display:inline-block;border:0;border-radius:11px;padding:12px 16px;font-weight:850;text-decoration:none;cursor:pointer}.primary{background:var(--blue);color:#fff}.panel{background:#fff;border:1px solid var(--line);border-radius:20px;padding:22px;box-shadow:0 8px 28px rgba(16,42,67,.05)}.search{display:grid;grid-template-columns:1fr auto;gap:10px;margin-bottom:18px}input{width:100%;padding:12px;border:1px solid var(--line);border-radius:11px;font:inherit}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:14px 10px;border-bottom:1px solid #edf2f7;white-space:nowrap}th{font-size:.74rem;color:var(--muted);letter-spacing:.06em;text-transform:uppercase}.name{font-weight:850}.mrn{font-size:.75rem;color:var(--blue);font-weight:800}.badge{display:inline-block;padding:6px 9px;border-radius:999px;background:#ecfdf3;color:var(--green);font-size:.72rem;font-weight:850}.empty{padding:35px;text-align:center;color:var(--muted)}.pagination{margin-top:18px}@media(max-width:850px){.shell{grid-template-columns:1fr}aside{display:none}.top{flex-direction:column}.search{grid-template-columns:1fr}}
</style></head>
<body><div class="shell"><aside><div class="brand"><div class="mark">CC</div><div><strong>CityCare</strong><small>Medical Center</small></div></div><nav><a href="{{ route('dashboard') }}">Dashboard</a><a class="active" href="{{ route('patients.index') }}">Patients</a><a href="{{ route('organization.index') }}">Organization</a></nav><form method="POST" action="{{ route('logout') }}">@csrf<button class="logout">Sign out</button></form></aside><main>
<div class="top"><div><div class="eyebrow">PATIENT MANAGEMENT</div><h1>Patient registry</h1><p class="muted">Search and access CityCare patient records securely from one operational workspace.</p></div>@can('permission','patients.create')<a class="btn primary" href="{{ route('patients.create') }}">+ Register patient</a>@endcan</div>
<div class="panel"><form class="search" method="GET" action="{{ route('patients.index') }}"><input name="search" value="{{ request('search') }}" placeholder="Search by name, MRN, phone or national ID…" autofocus><button class="btn primary">Search</button></form><div class="table-wrap"><table><thead><tr><th>Patient</th><th>MRN</th><th>Sex</th><th>Date of birth</th><th>Phone</th><th>Status</th><th></th></tr></thead><tbody>@forelse($patients as $patient)<tr><td><div class="name">{{ $patient->full_name }}</div><small class="muted">{{ $patient->email ?: 'No email recorded' }}</small></td><td><span class="mrn">{{ $patient->medical_record_number }}</span></td><td>{{ $patient->sex ?: '—' }}</td><td>{{ $patient->date_of_birth?->format('d M Y') ?: '—' }}</td><td>{{ $patient->phone ?: '—' }}</td><td><span class="badge">{{ ucfirst($patient->status) }}</span></td><td><a href="{{ route('patients.show', $patient) }}" style="color:var(--blue);font-weight:800;text-decoration:none">View →</a></td></tr>@empty<tr><td colspan="7"><div class="empty">No patients match your search.</div></td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $patients->links() }}</div></div>
</main></div></body></html>
